deploy_user: 'deploy'

# zzet.rbenv role: https://github.com/zzet/ansible-rbenv-role
rbenv_owner: 'deploy'
rbenv_group: 'deploy'
rbenv_users:
  - '{{ deploy_user }}'

rbenv:
  env: user
  version: v1.0.0
  default_ruby: 2.4.1
  rubies:
    - version: 2.4.1
    - version: 2.2.0

# vaulttect.zsh
zsh_users:
  - "{{ deploy_user }}"
zsh_ohmy_theme: robbyrussell

nodejs_version: '8.x'
nodejs_install_npm_user: '{{ deploy_user }}'

swapfile_size: 1GB
swapfile_swappiness: 0

# Postgres
postgresql_version: 9.6

postgresql_databases:
  - name: police_demos
    owner: deploy       # optional; specify the owner of the database
    hstore: yes         # flag to install the hstore extension on this database (yes/no)
    uuid_ossp: yes      # flag to install the uuid-ossp extension on this database (yes/no)
    citext: yes         # flag to install the citext extension on this database (yes/no)
    encoding: 'UTF-8'   # override global {{ postgresql_encoding }} variable per database
    lc_collate: 'en_US.UTF-8'   # override global {{ postgresql_locale }} variable per database
    lc_ctype: 'en_US.UTF-8'     #
  - name: thingsonreddit
    owner: deploy       # optional; specify the owner of the database
    hstore: yes         # flag to install the hstore extension on this database (yes/no)
    uuid_ossp: yes      # flag to install the uuid-ossp extension on this database (yes/no)
    citext: yes         # flag to install the citext extension on this database (yes/no)
    encoding: 'UTF-8'   # override global {{ postgresql_encoding }} variable per database
    lc_collate: 'en_US.UTF-8'   # override global {{ postgresql_locale }} variable per database
    lc_ctype: 'en_US.UTF-8'     #

postgresql_database_extensions:
  - db: police_demos
    extensions:
      - hstore
      - citext
      - cube
      - earthdistance
  - db: thingsonreddit
    extensions:
      - hstore
      - citext

postgresql_users:
  - name: deploy
