deploy_user: 'deploy'

# zzet.rbenv role: https://github.com/zzet/ansible-rbenv-role
rbenv_owner: 'deploy'
rbenv_group: 'deploy'
rbenv_users:
  - '{{ deploy_user }}'

rbenv:
  env: user
  version: v1.0.0
  default_ruby: 2.4.1
  rubies:
    - version: 2.4.1
    - version: 2.2.0

# vaulttect.zsh
zsh_users:
  - "{{ deploy_user }}"
zsh_ohmy_theme: robbyrussell
