- name: Ensure directory for settings is created
  file:
    path: '{{ pd_settings_dir }}'
    owner: deploy
    group: deploy
    state: directory


- name: Copy over localsettings
  template:
    src: localsettings.py.j2
    dest: '{{ pd_settings_dir }}/localsettings.py'
    owner: deploy
    group: deploy


- name: Install pd packages
  apt:
    name: '{{item}}'
    state: installed
  with_items:
    - postgresql-9.6-postgis-2.4
    - postgresql-9.6-postgis-2.4-scripts


- name: Copy over systemd configuration
  template:
    src: pd_gunicorn.service.j2
    dest: /etc/systemd/system/pd_gunicorn.service
    owner: deploy
    group: deploy


- name: Copy over .env.production for pd-frontend
  template:
    src: env.production.j2
    dest: '{{ pd_settings_dir }}/env.production'
    owner: deploy
    group: deploy
