---
- hosts: personal
  roles:
      - { role: common, tags: common }
      - { role: vaulttec.zsh, tags: zsh }
      - { role: zzet.rbenv, tags: rbenv }
      - { role: geerlingguy.nodejs, tags: node }
      - { role: kamaln7.swapfile, tags: swap }
      - { role: ANXS.postgresql, tags: postgresql }

# Lets encrypt
- hosts: personal
  tags: letsencrypt
  tasks:
      - include_role:
            name: thefinn93.letsencrypt
        vars:
            letsencrypt_webroot_path: '{{ role_item.webroot }}'
            letsencrypt_email: rudolphben@gmail.com
            letsencrypt_cert_domains:
                - '{{ role_item.domain }}'
        with_items:
            - { domain: bitbybit.benrudolph.com, webroot: /var/www/bitbybit/current/public }
            - { domain: benrudolph.com, webroot: /var/www/benrudolph/current/_site }
            - { domain: thingsonreddit.com, webroot: /var/www/thingsonreddit/current/public }
            - { domain: blog.thingsonreddit.com, webroot: /var/www/blog.thingsonreddit/current/_site }
            - { domain: first48.us, webroot: /var/www/police_demos/current/public }
        loop_control:
            loop_var: role_item

# Proxy
- hosts: personal
  tags: proxy
  roles:
      - role: jdauphant.nginx
        nginx_http_params:
            - gzip on
        nginx_configs:
            upstream:
                - upstream thingsonreddit { server unix:/var/www/thingsonreddit/shared/tmp/sockets/thingsonreddit-puma.sock fail_timeout=0; }
                - upstream police_demos { server unix:/var/www/police_demos/shared/tmp/sockets/police_demos-puma.sock fail_timeout=0; }
        nginx_sites:
            default:
                - listen 80 default_server
                - listen [::]:80 default_server
                - return 301 https://$host$request_uri
          # benrudolph.com: Jekyll
            benrudolph:
                - server_name benrudolph.com www.benrudolph.com
                - root /var/www/benrudolph/current/_site
                - listen 80
                - listen 443 ssl
                - index index.html index.htm
                - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
                - ssl_ciphers HIGH:!aNULL:!MD5
                # May have to comment out until letsencrypt has been run
                - ssl_certificate /etc/letsencrypt/live/benrudolph.com/fullchain.pem
                - ssl_certificate_key /etc/letsencrypt/live/benrudolph.com/privkey.pem
                - |
                  location / {
                    try_files $uri $uri/ =404;
                  }
          # Bit By Bit: Jekyll
            bitbybit:
                - server_name bitbybit.benrudolph.com
                - root /var/www/bitbybit/current/public
                - listen 80
                - listen 443 ssl
                - index index.html index.htm
                - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
                - ssl_ciphers HIGH:!aNULL:!MD5
                # May have to comment out until letsencrypt has been run
                - ssl_certificate /etc/letsencrypt/live/bitbybit.benrudolph.com/fullchain.pem
                - ssl_certificate_key /etc/letsencrypt/live/bitbybit.benrudolph.com/privkey.pem
                - |
                  location / {
                    try_files $uri $uri/ =404;
                  }

          # blog.thingsonreddit: Jekyll
            blog.thingsonreddit:
                - server_name blog.thingsonreddit.com
                - root /var/www/blog.thingsonreddit/current/_site
                - listen 80
                - listen 443 ssl
                - index index.html index.htm
                - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
                - ssl_ciphers HIGH:!aNULL:!MD5
                # May have to comment out until letsencrypt has been run
                - ssl_certificate /etc/letsencrypt/live/blog.thingsonreddit.com/fullchain.pem
                - ssl_certificate_key /etc/letsencrypt/live/blog.thingsonreddit.com/privkey.pem
                - |
                  location / {
                    try_files $uri $uri/ =404;
                  }

            # ThingsOnReddit: Rails
            thingsonreddit:
                - listen 80
                - listen 443 ssl
                - root /var/www/thingsonreddit/current/public
                - server_name thingsonreddit.com www.thingsonreddit.com
                - index index.html index.htm
                - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
                - ssl_ciphers HIGH:!aNULL:!MD5
                - ssl_certificate /etc/letsencrypt/live/thingsonreddit.com/fullchain.pem
                - ssl_certificate_key /etc/letsencrypt/live/thingsonreddit.com/privkey.pem
                - |
                  location ~ ^/(assets|packs|favicon|robots|static|sitemap.xml) {
                    try_files $uri =404;
                  }
                - |
                  location / {
                    proxy_pass http://thingsonreddit;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header Host $http_host;
                    proxy_set_header  X-Forwarded-Proto $scheme;
                    proxy_set_header  X-Forwarded-Ssl on;
                    proxy_set_header  X-Forwarded-Port $server_port;
                    proxy_set_header  X-Forwarded-Host $host;
                    proxy_redirect off;
                  }

            # Police Demos: Rails
            police_demos:
                - listen 80
                - listen 443 ssl
                - root /var/www/police_demos/current/public
                - server_name first48.us www.first48.us
                - index index.html index.htm
                - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
                - ssl_ciphers HIGH:!aNULL:!MD5
                - ssl_certificate /etc/letsencrypt/live/first48.us/fullchain.pem
                - ssl_certificate_key /etc/letsencrypt/live/first48.us/privkey.pem
                - |
                  location ~ ^/(assets|packs|favicon|robots|static|sitemap.xml) {
                    try_files $uri =404;
                  }
                - |
                  location / {
                    proxy_pass http://police_demos;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header Host $http_host;
                    proxy_set_header  X-Forwarded-Proto $scheme;
                    proxy_set_header  X-Forwarded-Ssl on;
                    proxy_set_header  X-Forwarded-Port $server_port;
                    proxy_set_header  X-Forwarded-Host $host;
                    proxy_redirect off;
                  }
