- name: Install common packages
  apt:
    name: '{{item}}'
    state: installed
  with_items:
    - libpq-dev
    - unzip
    - zip
    - git
    - zsh

- name: Deploy group
  group:
    name: deploy
    state: present

- name: Setup deploy user
  user:
    name: deploy
    group: deploy
    shell: /bin/zsh

- name: Set authorized keys
  authorized_key:
    user: deploy
    state: present
    key: '{{ item }}'
  with_lines:
    - "cat pub_keys/*"

- name: Own /var/www
  file:
    path: /var/www
    owner: deploy
    group: deploy
    state: directory
