- name: Fetch Yarn pkg
  shell: |
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

- name: Update apt
  shell: |
    apt-get update

- name: Install common packages
  apt:
    name: '{{item}}'
    state: installed
  with_items:
    - libpq-dev
    - unzip
    - zip
    - git
    - zsh
    - yarn
    - htop

- name: Deploy group
  group:
    name: deploy
    state: present

- name: Setup deploy user
  user:
    name: deploy
    group: deploy
    shell: /bin/zsh
    password: EPkP5waGinsL2

- name: Allow deploy group to have sudo permissions
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%deploy'
    line: '%deploy ALL=(ALL)      NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set authorized keys
  authorized_key:
    user: deploy
    state: present
    key: '{{ item }}'
  with_lines:
    - "cat pub_keys/*"

- name: Own /var/www
  file:
    path: /var/www
    owner: deploy
    group: deploy
    state: directory

- name: Disallow password SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
